language: generic
deploy:
  provider: s3
  access_key_id: AKIAJVQZ3GB6RE6EJBUQ
  secret_access_key:
    secure: j/Xl5CWiTmJTc9mlX9/7R42FobpwZu5odhfJu6LlU80solzdN2gKVvXw4c8AeY7/s1pY/v9Tcus3VtTsIg+TNGJJ9GrH8bNjCAmqB0EE95/oKEGcEL7QARl5q4KIiQfk/kHvN8v4pXjfyzZeZ4Q2d4XrT/6J75u3A4n7CZ0PQ4bz4ZcsfciuoWHXFK45YWpjcD3yLnHWjzOaf/6wU/QYSVHLQDN8NWWsWTwG3wn00maodfwWt0C5bYCbBoVQ10aF5RgiSdCuy5/OnAhz6dr/S/N/vl+3AF9puCNkypCxMTJ4WSbYTN1OmiMnzwCTT/hPPGdnIuW6KYBQyEU1bAoP7g3qfowfzxBbntTYpKykUx518XreizspcPjW5S4+p61AMZcyzZNKPuFDa6CzqI8puqBNEA+gqvQxqKbobbVCnpfY2nSCw3MGyPXm2r6kuF7mdygtmUIVgUXTRlDptNXhJygTtAb4JEoUmQf/IM9IJPpMEon7I+bETdhvkYsKhA7FVTqep1ylTVgnfnkzOdDD5b6uTSZsswHOhkS5WBX2NkD73O49Nh5OwuPUotf2BNF7WEfHnS2Pr5ScBBwaPFaD8yaWMJeGSSUJVuekCwQ0HjxXdvaSZ8JcedNImlq24+WSdWuJE0BzuTSYVdoWfMqk7qJUgzI4kgpP7BNWdB5AVy0=
  bucket: production-nyclibraries.org
  acl: public_read
  on:
    branch: production
